openapi: 3.0.0
info:
  title: 1752-TestMock
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /addresses:
    get:
      summary: addresses
      tags: []
      responses: {}
      operationId: get-addresses
components:
  schemas:
    '400':
      title: 400
      type: object
      properties:
        code:
          type: string
          example: attribute-level 400 message
        test:
          type: string
